apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - templates/disallow-tags.yaml
  - templates/psp-host-network.yaml
  - templates/psp-privileged.yaml
  - templates/required-resources.yaml
  - constraints/block-host-network.yaml
  - constraints/block-root-user.yaml
  - constraints/disallow-latest-tag.yaml
  - constraints/require-limits.yaml
