# ArgoCD app: Deploy ConstraintTemplates + Constraints - Gatekeeper Policies
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper-policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/datpn02/w10-lab.git
    targetRevision: main
    path: gatekeeper
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
