apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: w10-api-signed
spec:
  images:
    - glob: "ghcr.io/datpn02/w10-api**"
  authorities:
    - name: cosign-public-key
      key:
        hashAlgorithm: sha256
        data: |
          -----BEGIN PUBLIC KEY-----
          MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEbbW6YZUe9ryhA3gGeWkNqOvtJghf
          gZ/0aqCpbgtBK74nR89bfsSHrZbNvx5NOX9UALHRdc9QXlSbVJiAtM740Q==
          -----END PUBLIC KEY-----
